language: objective-c
osx_image: xcode8
before_install:
  - brew update >/dev/null
  - brew list autoconf || brew install autoconf
  - brew list automake || brew install automake
  - brew list carthage || brew install carthage
  - brew uninstall libtool && brew install libtool
  - carthage bootstrap
  - cd libmpdclient
  - sed -i .bak 's/libtoolize/glibtoolize/g' autogen.sh
  - ./autogen.sh --disable-documentation
  - make
  - cd ..
install:
  - version_number=`git describe --tags --abbrev=0 2>/dev/null || echo 0.0`
  - if [[ $? != 0 ]]; then version_number="0.0"; fi
  - agvtool new-version -all $TRAVIS_BUILD_NUMBER
  - agvtool new-marketing-version $version_number
  - xcodebuild -target kmbmpdc -configuration Release
before_script:
  - brew list swiftlint || brew install swiftlint
script:
  - cd kmbmpdc
  - swiftlint
